### ISSUE TITLE
如何参与项目维护

### ISSUE THREAD

**Issue by myrfy001** [ch32-rs/ch32-rs#1]
您好：
我最近在使用ch32-rs社区提供的PAC库进行开发，但发现目前由svd2rust生成的PAC库存在缺陷，在浏览https://github.com/ch32-rs/ch32-rs
项目后，发现项目中并没有svd文件。请问您有计划像stm32-rs社区那样，通过一系列patch来不断修复svd文件中的bug吗？或者我有什么方式可以参与到这个项目中来维护完善ch32-rs吗？

谢谢

**Comment by andelf** [comment]
Fixed by adding patch skeletons. 
Check out https://github.com/ch32-rs/ch32-rs/tree/main/svd
