### ISSUE TITLE
Adding "derivedFrom" for various types

### ISSUE THREAD

**Issue by Slappy2022** [ch32-rs/ch32-rs#10]
Consider `UART1` in [CH58Xxx.svd](https://github.com/ch32-rs/ch32-rs/blob/main/svd/vendor/CH58Xxx.svd), I believe we want the addition of `derivedFrom="UART0"`, giving us:
```
<peripheral derivedFrom="UART0">
   <name>UART1</name>
```

Similarly for other UARTs and likely some other types. Any thoughts on how best to approach this? e.g. shall we just send around PRs as needed?

**Comment by andelf** [comment]
You can patch it using [svdtools](https://github.com/stm32-rs/svdtools).
https://github.com/ch32-rs/ch32-rs/blob/main/devices/ch58x.yaml

```
# Replace peripheral registers by a 'deriveFrom'.
# This is used when e.g. UART4 and UART5 are both independently defined,
# but you'd like to make UART5 be defined as derivedFrom UART4 instead.
_derive:
    # The KEY peripheral looses all its elements but 'interrupt', 'name',
    # and 'baseAddress', and it is derivedFrom the VALUE peripheral.
    # Peripherals that were 'deriveFrom="KEY"' are now 'deriveFrom="VALUE"'.
    UART5: UART4
```

**Comment by Slappy2022** [comment]
Nice!

ch32-rs-nightlies is currently out of date, did you have some pending changes or shall I send some cleanup PRs?

**Comment by andelf** [comment]
I'm planning to schedule a new release this week.😁

PRs are welcome.

**Comment by andelf** [comment]
Clsoe as implemented
