### ISSUE TITLE
CH32V003 (RV32EC) support

### ISSUE THREAD

**Issue by csarn** [ch32-rs/ch32-rs#14]
The README states 

    Support CH32V003 family (RV32EC is not supported by Rust)

but `rustc --target=riscv32i-unknown-none-elf -Ctarget-feature=help` shows:

    Features supported by rustc for this target:
        a                    - 'A' (Atomic Instructions).
        c                    - 'C' (Compressed Instructions).
        d                    - 'D' (Double-Precision Floating-Point).
        e                    - Implements RV32E (provides 16 rather than 32 GPRs).
        f                    - 'F' (Single-Precision Floating-Point).
        m                    - 'M' (Integer Multiplication and Division).
        v                    - 'V' (Vector Extension for Application Processors).

which seems to suggest that the `embedded` base ISA is supported by using `-Ctarget-feature=e`.

Is there something I'm misunderstanding here? Or would that mean we can actually use rust with the Ch32V003?

**Comment by andelf** [comment]
Many thanks. I'll check if we can compile for ch32v003.

**Comment by cathiele** [comment]
with this ``.cargo/config.toml```:

```
[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "target-feature=+e",
  "-C", "target-feature=+c",
]
```

i get:

```
LLVM ERROR: Codegen not yet implemented for RV32E
```

```rustc --target=riscv32i-unknown-none-elf -Ctarget-feature=help``` shows on my installation the same "supported Features"

what is still missing is this patch in llvm: https://reviews.llvm.org/D70401

**Comment by cathiele** [comment]
the next step for me is to compile rustc with this patched llvm version that is linked in the patch-discussion:

https://github.com/kekcheburec/llvm-project/tree/5cf27e03900c06c0f374a8f3a6e65a817ce70607

**Comment by andelf** [comment]
@cathiele Thanks! 
AFAIK, llvm's riscv32ec support is only partially implemented.

**Comment by cathiele** [comment]
TLTR: it compiles but i can not link the resulting files

i compiled a custom rust-toolchain with the patched llvm and can finally compile with the following `config.toml`:

```
[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "target-feature=+e",
  "-C", "target-feature=+c",
  "-C", "linker=riscv64-unknown-elf-ld",
  "-C", "link-arg=-melf32lriscv",
]
```
i had to configure the rust-lld linker to use the gcc-version because there is no lld support.

But the linker complains a missing symbol:

```
note: riscv64-unknown-elf-ld:link.x:41: undefined symbol `default_start_trap' referenced in expression
```

that symbol should be defined in `riscv-rt` (0.11.00 which compiles fine and creates a .rlib file.

The symbol is defined in:

https://github.com/rust-embedded/riscv-rt/blob/92568c17eac373da76ded423dfd735c7376e77c8/asm.S

but in this file are references to the upper 16 Registers that don't exist in rv32e...

Any ideas?

**Comment by cathiele** [comment]
Its blinking :-)

i fixed the missing symbol by defining an empty function:

```
#[no_mangle]
fn default_start_trap() {

}
```

of course this is just a hacky workaround...

**Comment by cathiele** [comment]
This is my small test Project that works fine on the 8-Pin ch32v003:

https://github.com/cathiele/ch32v003-rust-blink

**Comment by csarn** [comment]
No idea if this was one of you, but someone published a blog post series on getting Rust working for the ch32v003: https://noxim.xyz/blog/rust-ch32v003/

**Comment by cathiele** [comment]
> No idea if this was one of you, but someone published a blog post series on getting Rust working for the ch32v003: https://noxim.xyz/blog/rust-ch32v003/

Very good explained! Would have saved me some time.

**Comment by andelf** [comment]
Now we have a working nightly(dev) branch for riscv32ec https://github.com/ch32-rs/rust 🥳

**Comment by andelf** [comment]
Close as Rust nightly has already introduced LLVM rv32ec update.

Usage: https://github.com/ch32-rs/ch32v00x-hal
