### ISSUE TITLE
How can I control GPIO using ch57x crate?

### ISSUE THREAD

**Issue by za-songguo** [ch32-rs/ch32-rs#16]
I am new to embedded development.
In `ch32v3` crate, I can use `ch32v3::ch32v30x::gpioa::outdr::ODR4_W` to set the output data of PA4, but I haven't found a similar type in `ch57x` crate. I only found `ch57x::ch57x::sys::pa_out::PA_OUT_0_W` and `ch57x::ch57x::sys::pa_out::PA_OUT_1_W` in it. How can I set the output data of PA4? Does anyone have an idea?

**Comment by andelf** [comment]
I haven't tested my CH572 board yet.
As far as I know, CH57x/CH58x/CH59x BLE chips use a different GPIO register layout from CH32V30x. (GPIOs are located in SYS, there's no GPIO register group).
You can refer to the RM manual.

**Comment by za-songguo** [comment]
> I haven't tested my CH572 board yet. As far as I know, CH57x/CH58x/CH59x BLE chips use a different GPIO register layout from CH32V30x. (GPIOs are located in SYS, there's no GPIO register group). You can refer to the RM manual.

I think I should write something to `ch57x::ch57x::sys::pa_out::PA_OUT_SPEC`, it seems I should write `0x10` to `R8_PA_OUT_0` register to control PA4.
WCH's datasheet is not detailed and I don't have a CH573 board to test it.
If I am right, is there a way to make the operation more convenient, such as adding a Rust type for each GPIO port?

**Comment by andelf** [comment]
Yes, WCH's RM/DS doc is not detailed.
A good reference is the EVT code pack.
Sorry, there's no -hal crate yet.
