### ISSUE TITLE
No firmware for Micropython for this ch32v003

### ISSUE THREAD

**Issue by anandr16910** [ch32-rs/ch32-rs#19]
Running and flashing this microcontroller board with MicroPython requires firmware associated with this part number CH32V003. Unfortunately, [https://micropython.org/download/] or [https://github.com/micropython/micropython?tab=readme-ov-file#supported-platforms--architectures] does not have firmware for this Microcontroller.

Please help in creating a firmware for supporting micropython.

**Comment by andelf** [comment]
This is not the official WCH's repo for CH32V003 or any other of its MCUs.
This is the Rust Embedded framework support for WCH's MCUs, managed by the ch32-rs team.
You can fire an issue at https://github.com/openwch/ch32v003.

**Comment by andelf** [comment]
Close as this is not an issue of this repo
