### ISSUE TITLE
error when taking peripheral, using example for CH32V3

### ISSUE THREAD

**Issue by orangecms** [ch32-rs/ch32-rs#2]
I am getting the following error:

```
error[E0599]: `Peripherals` is not an iterator
      --> src/main.rs:62:50
       |
62     |     let mut peripherals = ch32v30x::Peripherals::take().unwrap();
       |                                                  ^^^^ `Peripherals` is not an iterator
       |
      ::: /home/dama/.cargo/registry/src/github.com-1ecc6299db9ec823/ch32v3-0.1.4/src/ch32v30x/mod.rs:138670:1
       |
138670 | pub struct Peripherals {
       | ---------------------- doesn't satisfy `Peripherals: Iterator`
       |
       = note: the following trait bounds were not satisfied:
               `Peripherals: Iterator`
               which is required by `&mut Peripherals: Iterator`

For more information about this error, try `rustc --explain E0599`.
```

It looks like the generated `Cargo.toml` is missing the feature declaration for `"critical-section"`.

**Comment by andelf** [comment]
Thanks. I forgot to publish to cargo.
It should be fixed now.

Currently, I'm working on a hal crate for my CH32V203 board.

**Comment by orangecms** [comment]
Awesome, thank you!

I started this here, though I'm struggling with the linker script:
https://github.com/orangecms/ch32v307-rust

**Comment by andelf** [comment]
Check out https://github.com/ch32-rs/ch32v203-demo
It's a simple blinky on a CH32V203 board from https://github.com/metro94/FlappyBoard.
