### ISSUE TITLE
CH32V003: TIM2RST missing from APB1PRSTR register definition

### ISSUE THREAD

**Issue by agausmann** [ch32-rs/ch32-rs#20]
![image](https://github.com/ch32-rs/ch32-rs/assets/6611767/3271a7ff-1dbc-4af5-b97c-efde97d51fb3)

https://github.com/ch32-rs/ch32-rs/blob/b9d28b17c9f0a5ff55f7baa8f7f83084bf9345e7/svd/vendor/CH32V003xx.svd#L494-L523

**Comment by agausmann** [comment]
My workaround for now:

```rust
apb1prstr.modify(|r, w|
    // w.tim2rst().set_bit()
    unsafe { w.bits(r.bits() | 0x1) }
);
apb1prstr.modify(|r, w|
    // w.tim2rst().clear_bit()
    unsafe { w.bits(r.bits() & !0x1) }
);
```

**Comment by andelf** [comment]
Thanks for the report. This is easy to fix using yaml patch. I'll check this later.
