### ISSUE TITLE
how is the svd binary installed?

### ISSUE THREAD

**Issue by markushx** [ch32-rs/ch32-rs#7]
`cargo install svd` mentioned in 
https://github.com/ch32-rs/ch32-rs/blob/main/scripts/generate.sh#L6 does not install anything.

**Comment by andelf** [comment]
Use the python version instead.
I observed some in-compatibility of the two implementations.

**Comment by markushx** [comment]
Is it svdtools?
I tried `cargo install svdtools` and that reports:
```
mab@mab-2 ch32-rs % ./scripts/generate.sh
+ ./scripts/makecrates.py -y devices
Going to create/update the following directories:
ch56x/, ch32v2/, ch32v1/, ch57x/, ch32v3/, ch58x/
+ svdtools patch devices/ch56x.yaml
[2022-12-11T17:02:51Z ERROR svdtools::cli] by svdtools (0.2.7)
    
    Caused by:
        0: Processing device `CH569`
        1: Adding peripheral `SERDES`
        2: Under key `description`
        3: Value is not a string: Null
```
Is that the incompatibility you mentioned?

description was easy to patch. But then:
```
[2022-12-11T17:03:16Z ERROR svdtools::cli] by svdtools (0.2.7)
    
    Caused by:
        0: Processing device `CH569`
        1: Adding peripheral `SERDES`
        2: `Build error: `bit_range` must be initialized
        3: `bit_range` must be initialized
```
which seem to be related to https://github.com/stm32-rs/svdtools/issues/113.

**Comment by markushx** [comment]
When disabling the CH5xx devices in the generate.sh script, I am able to create the PACs for the other devices with the cargo installed svdtools. (I am currently trying out the CH32V003.

**Comment by andelf** [comment]
@markushx  Thanks, I'll fix the scripts.

**Comment by andelf** [comment]
Close as finished.
