### ISSUE TITLE
 ch58x::Peripherals missing GPIO

### ISSUE THREAD

**Issue by Slappy2022** [ch32-rs/ch32-rs#9]
Is this expected? I see `FieldReader`'s named like `PB_OUT_0_R` in `ch32-rs-nightlies/ch58x/src/ch58x/mod.rs`, perhaps this is how they're intended to be accessed/mutated/etc?

**Comment by andelf** [comment]
According to the datasheet of CH58x,
All GPIOs are located in `SYS`.
A patch for svd file is needed.

**Comment by andelf** [comment]
Since some CH5xx chips use this scheme, I prefer to name it gpio_v0.

**Comment by andelf** [comment]
Close as fixed in v0.2.0.
